import { Bot, CheckCircle2, AlertTriangle, Shield, Lightbulb } from 'lucide-react';

export default function AIAnalysis() {
  return (
    <div className="animate-fade-in max-w-4xl">
      <div className="glass-card rounded-lg p-8 border-l-4 border-l-accent">
        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="w-8 h-8 rounded-lg bg-accent/20 flex items-center justify-center">
            <Bot size={18} className="text-accent" />
          </div>
          <div>
            <h3 className="font-display font-bold text-text-primary">Portfolio Assessment — Wise Auto Brokers</h3>
            <p className="text-xs text-text-secondary">Generated by AF Portfolio Intelligence | April 14, 2026</p>
          </div>
        </div>

        {/* Recommendation Banner */}
        <div className="bg-accent/10 border border-accent/20 rounded-lg px-5 py-3 mb-8">
          <span className="text-sm font-display font-bold text-accent">Overall Recommendation: CONDITIONAL BID at $1,059,800</span>
        </div>

        {/* Narrative */}
        <div className="prose prose-sm prose-invert max-w-none space-y-6">
          <p className="text-sm text-text-primary/90 leading-relaxed">
            This 142-loan portfolio from Wise Auto Brokers presents a moderately attractive acquisition
            opportunity with above-average confidence. The portfolio is concentrated in Southeast markets
            where AF has strong servicing infrastructure, which supports the favorable servicing cost projections.
          </p>

          {/* Key Strengths */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <CheckCircle2 size={16} className="text-emerald-400" />
              <h4 className="font-display font-bold text-emerald-400 text-sm uppercase tracking-wider">Key Strengths</h4>
            </div>
            <ul className="space-y-2.5 ml-6">
              {[
                '54% of borrowers classified as "Good Payer" based on payment momentum analysis — above the 48% average for purchased portfolios',
                'Vehicle mix is weighted toward trucks and SUVs (52%), which show slower depreciation and higher recovery rates in AF\'s historical data',
                'Average seasoning of 11.3 months provides meaningful revealed payment behavior data',
                'Dealer has sold 2 prior portfolios to AF, both of which outperformed initial projections by 4-6%',
              ].map((text, i) => (
                <li key={i} className="text-sm text-text-primary/80 leading-relaxed flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" />
                  {text}
                </li>
              ))}
            </ul>
          </div>

          {/* Key Risks */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <AlertTriangle size={16} className="text-amber-400" />
              <h4 className="font-display font-bold text-amber-400 text-sm uppercase tracking-wider">Key Risks</h4>
            </div>
            <ul className="space-y-2.5 ml-6">
              {[
                '18 loans (12.7%) are currently 30+ DPD — higher than AF\'s comfort threshold of 10%',
                'Georgia concentration (42%) creates geographic risk if the Atlanta metro economy weakens',
                '23 loans have LTV > 130%, indicating limited recovery value if defaults occur early',
                'Credit score distribution is bimodal — a cluster at 580-620 and another at 490-520 — the lower cluster historically defaults at 2.3x the rate',
              ].map((text, i) => (
                <li key={i} className="text-sm text-text-primary/80 leading-relaxed flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-1.5 shrink-0" />
                  {text}
                </li>
              ))}
            </ul>
          </div>

          {/* Confidence Assessment */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Shield size={16} className="text-accent" />
              <h4 className="font-display font-bold text-accent text-sm uppercase tracking-wider">Confidence Assessment</h4>
            </div>
            <p className="text-sm text-text-primary/80 mb-3 ml-6">
              Model confidence is <span className="text-emerald-400 font-semibold">HIGH (87th percentile)</span> based on:
            </p>
            <ul className="space-y-1.5 ml-6">
              {[
                'All Ring 1 features available',
                'Ring 2 enrichment complete (Black Book values, VIN decode, geo data)',
                'Dealer historical performance data available (2 prior deals)',
                'Ensemble model agreement: all three default models converge within 3.2 percentage points',
              ].map((text, i) => (
                <li key={i} className="text-sm text-text-primary/80 flex items-center gap-2">
                  <CheckCircle2 size={12} className="text-emerald-400 shrink-0" /> {text}
                </li>
              ))}
            </ul>
            <div className="mt-4 ml-6 bg-card/50 rounded-lg p-3">
              <p className="text-xs text-text-secondary">
                The 90% confidence interval on ENPV is <span className="text-text-primary font-mono">$934,000 — $1,178,000</span>.
              </p>
              <p className="text-xs text-text-secondary mt-1">
                At the recommended bid of <span className="text-accent font-mono">$1,059,800</span>, the portfolio is projected to be
                profitable under all scenarios except severe stress (probability-weighted at 10%).
              </p>
            </div>
          </div>

          {/* Suggested Conditions */}
          <div>
            <div className="flex items-center gap-2 mb-3">
              <Lightbulb size={16} className="text-violet-400" />
              <h4 className="font-display font-bold text-violet-400 text-sm uppercase tracking-wider">Suggested Conditions</h4>
            </div>
            <ul className="space-y-2.5 ml-6">
              {[
                'Verify insurance coverage status on the 18 delinquent loans before closing',
                'Request updated payment status from dealer (tape is 12 days old)',
                'Consider excluding the 4 loans with balance > $25,000 and DPD > 45 — these represent $112,400 in balance with low recovery probability',
              ].map((text, i) => (
                <li key={i} className="text-sm text-text-primary/80 leading-relaxed flex items-start gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-violet-400 mt-1.5 shrink-0" />
                  {text}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="mt-8 pt-4 border-t border-border flex items-center justify-between">
          <span className="text-[10px] text-text-secondary">Generated in 2.4s | Model version 3.2.1 | 142 loans analyzed</span>
          <div className="flex gap-2">
            <button className="px-3 py-1.5 rounded border border-border text-xs text-text-secondary hover:text-text-primary transition-colors">Export PDF</button>
            <button className="px-3 py-1.5 rounded border border-border text-xs text-text-secondary hover:text-text-primary transition-colors">Regenerate</button>
          </div>
        </div>
      </div>
    </div>
  );
}
